// <auto-generated />
using System;
using Habit_Tracker_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Habit_Tracker_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260125213012_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.Habit", b =>
                {
                    b.Property<long>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("HabitId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HabitName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("habit_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("priority");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("HabitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "HabitName")
                        .IsUnique();

                    b.ToTable("HABITS");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.HasKey("CategoryId");

                    b.ToTable("HABIT_CATEGORIES");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LogId"));

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("LogId");

                    b.HasIndex("HabitId", "LogDate")
                        .IsUnique();

                    b.ToTable("HABIT_LOG");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitReminder", b =>
                {
                    b.Property<long>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reminder_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ReminderId"));

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<TimeSpan>("ReminderTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("reminder_time");

                    b.HasKey("ReminderId");

                    b.HasIndex("HabitId");

                    b.ToTable("HABIT_REMINDER");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitSchedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("day_of_week");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("HabitId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("HABIT_SCHEDULE");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitStreak", b =>
                {
                    b.Property<long>("StreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("streak_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StreakId"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int")
                        .HasColumnName("current_streak");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<DateOnly?>("LastCompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_completed_date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int")
                        .HasColumnName("longest_streak");

                    b.HasKey("StreakId");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.ToTable("HABIT_STREAKS");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mobile_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.UserOtp", b =>
                {
                    b.Property<long>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("otp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OtpId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("otp_code_hash");

                    b.Property<string>("OtpType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("otp_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OtpId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("USER_OTP");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.Habit", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.HabitCategory", "HabitCategory")
                        .WithMany("Habits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Habit_Tracker_Backend.Models.Classes.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitLog", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.Habit", "Habit")
                        .WithMany("HabitLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitReminder", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.Habit", "Habit")
                        .WithMany("HabitReminders")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitSchedule", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.Habit", "Habit")
                        .WithMany("HabitSchedules")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitStreak", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.Habit", "Habit")
                        .WithOne("HabitStreak")
                        .HasForeignKey("Habit_Tracker_Backend.Models.Classes.HabitStreak", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.UserOtp", b =>
                {
                    b.HasOne("Habit_Tracker_Backend.Models.Classes.User", "User")
                        .WithMany("UserOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.Habit", b =>
                {
                    b.Navigation("HabitLogs");

                    b.Navigation("HabitReminders");

                    b.Navigation("HabitSchedules");

                    b.Navigation("HabitStreak")
                        .IsRequired();
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.HabitCategory", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("Habit_Tracker_Backend.Models.Classes.User", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("UserOtps");
                });
#pragma warning restore 612, 618
        }
    }
}
